/*
The function fetchUserData() will trigger a custom event userDataReady 
when the data has been fetched and is ready to be parsed. 
You can access the JSON data with event.detail.jsonText inside your code. 

** Your task is to listen to the event and update the HTML according to the data.

Write your code in the messages-as-json.js file inside the exercises/03_javascript/ex5 directory.
You can find the HTML in the index.html file inside this directory. Open this file in your browser and open the developer console to see any errors in your code. 
Do not edit this file!

Listen to the userDataReady event on the document and parse the JSON data into a JavaScript object. 
The JSON data format can be found in the fetch-users.js file, but do not edit this file. 
The data is an array of user objects, and your task is to loop through the data and create new user info HTML inside the contacts div Pay attention to the template tag inside index.html and replace its content with the actual user data. Remember to clone the template content for each user using template.content.cloneNode(true).

The function fetchUserData() is not called anywhere. 
Add a call to it as the last line of your code. This line must be outside of your event handler!

*/

const headNode = document.getElementById('contacts');

const contactTemplate = document.getElementById('user-card-template');

// console.log(headNode);
// console.log(contactTemplate);

document.addEventListener('userDataReady', (e) => {
    const jData = e.detail.jsonText;
    let dataObject = JSON.parse(jData);

    // console.log(typeof(dataObject));
    // console.log(dataObject.length);

    dataObject.forEach(element => {
        updatePageFromJsonData(element)
    });
})


const updatePageFromJsonData = (e) => {

    const para = document.createElement('div');
    para.innerHTML = contactTemplate.innerHTML;

    para.getElementsByClassName('card')[0].getElementsByTagName('h1')[0].innerHTML = e.firstName + " " + e.lastName;
    para.getElementsByClassName('card')[0].getElementsByTagName('img')[0].src = e.avatar; 
    para.getElementsByClassName('card')[0].getElementsByTagName('img')[0].alt = e.firstName + " " + e.lastName;
    para.getElementsByClassName('card')[0].getElementsByClassName('title email')[0].innerHTML = e.email;
    para.getElementsByClassName('card')[0].getElementsByClassName('address')[0].children[0].innerHTML = e.address.streetAddress;
    para.getElementsByClassName('card')[0].getElementsByClassName('address')[0].children[1].innerHTML = e.address.zipCode + " " + e.address.city;
    para.getElementsByClassName('card')[0].getElementsByClassName('address')[0].children[2].innerHTML = e.address.country;
    para.getElementsByClassName('card')[0].getElementsByClassName('phone')[0].children[0].innerHTML = e.phoneNumber;
    para.getElementsByClassName('card')[0].getElementsByClassName('homepage')[0].children[0].href = e.homepage;
    para.getElementsByClassName('card')[0].getElementsByClassName('homepage')[0].children[0].innerHTML = e.homepage;

    headNode.appendChild(para);
}


fetchUserData();